### ISSUE TITLE
Clean up Custom Fields by Adding "Requested Lab" and "Inquiry"

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#17]
<img width="486" alt="screen shot 2016-02-16 at 10 03 20 am" src="https://cloud.githubusercontent.com/assets/14278320/13079955/a70610c4-d494-11e5-870f-9ba9b4922ea8.png">

**Comment by adamsfallen** [comment]
I think it'll remain and be retitled "Requested Lab" or something similar (to distinguish it from the lab to which the inquiry is ultimately assigned) and that I'll move the "Inquiry" to its own custom field alongside "Requested Lab", so that it's at the top of the Lead page and preserved. Sound good to you?
