### ISSUE TITLE
For "Partner with Lab" select Lab and assign new lab question

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#46]
The current process:
1. "investor" selects lab (in this case Sandia)
2. inquiry is pending and move to open
3. in open, there is drop down to "assign lab". 
4. new lab assigned "NREL"
What is expected behavior?
- routing now to NREL instead of Sandia (end user selected)?
- tracking of re-assignment from Sandia to NREL?
- email notification trigger to NREL account contact?

**Comment by adamsfallen** [comment]
Yes this is an excellent question - keep in mind right now we are tracking both the _requested lab_ (Sandia) and the _assignee_ (NREL).
1. If the assignee changed in the CRM then it would enter the routing flow for that assignee (NREL).
2. Because we track both pieces of data, it's certainly possible to run metrics against it, however two caveats: (a) I can't say how simple it would be to visualize that data in simple charts or graphs, although we can imagine ways of doing it by exporting the data from the CRM. (b) If there were multiple reassignments (say from Sandia -> NREL -> Brookhaven) I'm not sure the full train of assignments would be tracked (just the first and last).
3. The email would fire to Sandia when the system assigned Sandia, and if Sandia reassigned, it would fire again to NREL (and again if it was reassigned). The email flow is triggered when a user is assigned (part of the simplicity of treating labs as users is that we can do stuff like this, if that makes sense).

Feel free to close if I've answered your questions.

**Comment by alexpelletier** [comment]
@adamsfallen - can you test this workflow yourself? the variable of pending to open is when it triggers. Just try it and see what you think. It seems like we could simplify somehow. I will be more specific when I have time to check.
@lukad03 could you look too and see what you think? 
workflow could be simplified.
